/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:afffc1f0-3812-41bb-b16a-8ca1291fa35d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_KXU89tFz2",
    "aws_user_pools_web_client_id": "2jovet4huspef8bldhtm24gsq6",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://e4rirw7ranbtneoopzwukfqv7e.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3fibd2sbg5d55psd5winh4j56y",
    "aws_user_files_s3_bucket": "plentyofpups-pics71456-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
